version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
    ports:
      - '5432:5432'
  chat-backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./chat-backend
    volumes:
      - /app/node_modules
      - ./chat-backend:/app
  nginx:
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - 80:80
  pgadmin:
    image: 'dpage/pgadmin4'
    ports:
      - '5555:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=hussein_demo_Ea625xpCJWhC@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=password
