version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
    ports:
      - '5432:5432'
  chat-backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./chat-backend
    volumes:
      - ./chat-backend:/app
      - /app/node_modules
  nginx:
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - 80:80
  chat-frontend:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./chat-frontend
    volumes:
      - /app/node_modules
      - ./chat-frontend:/app
    # polling setting for Docker. activate auto reload when file change.
    environment:
      - CHOKIDAR_USEPOLLING=true
  pgadmin:
    image: 'dpage/pgadmin4'
    ports:
      - '5555:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=hussein_demo_Ea625xpCJWhC@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=password
