version: '3'
services:
  chat-backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./chat-backend
    volumes:
      - /chat-backend/node_modules
      - ./chat-backend:/app
    ports:
      - 3000:3000
